#!/usr/bin/env python3
# tools/gen_digits.py
"""Generate firmware/assets/digits.py: 14x24 seven-segment digit bitmasks.

Deterministic pure-integer rendering -- no fonts, no PIL -- so the committed
module byte-matches this generator on any machine (tests/test_digit_assets.py
enforces it). Run with --stdout to print instead of writing the file.
"""
import sys
from pathlib import Path

W, H, T = 14, 24, 3          # grid width, height, stroke thickness

# (row0, row1, col0, col1) half-open pixel rectangles
SEGMENTS = {
    "A": (0, T, 0, W),                     # top bar
    "G": ((H - T) // 2, (H - T) // 2 + T, 0, W),   # middle bar
    "D": (H - T, H, 0, W),                 # bottom bar
    "F": (0, H // 2, 0, T),                # top-left
    "B": (0, H // 2, W - T, W),            # top-right
    "E": (H // 2, H, 0, T),                # bottom-left
    "C": (H // 2, H, W - T, W),            # bottom-right
}

DIGIT_SEGS = {
    0: "ABCDEF", 1: "BC", 2: "ABGED", 3: "ABGCD", 4: "FGBC",
    5: "AFGCD", 6: "AFGECD", 7: "ABC", 8: "ABCDEFG", 9: "ABCDFG",
}


def render(digit):
    rows = [0] * H
    for seg in DIGIT_SEGS[digit]:
        r0, r1, c0, c1 = SEGMENTS[seg]
        for r in range(r0, r1):
            for c in range(c0, c1):
                rows[r] |= 1 << c
    return tuple(rows)


def module_text():
    lines = ['"""Generated by tools/gen_digits.py -- do not edit.',
             "",
             "Ten digits 0-9 as 24 row bitmasks each; bit i = column i of 14.",
             '"""',
             "DIGITS = ("]
    for d in range(10):
        rows = render(d)
        lines.append("    (  # %d" % d)
        for i in range(0, len(rows), 6):
            chunk = ", ".join("0x%04x" % m for m in rows[i:i + 6])
            lines.append("        " + chunk + ",")
        lines.append("    ),")
    lines.append(")")
    return "\n".join(lines) + "\n"


def main():
    text = module_text()
    if "--stdout" in sys.argv:
        sys.stdout.write(text)
        return
    out = Path(__file__).resolve().parent.parent / "firmware" / "assets"
    out.mkdir(exist_ok=True)
    (out / "__init__.py").touch()
    (out / "digits.py").write_text(text)
    print("wrote", out / "digits.py")


if __name__ == "__main__":
    main()
